baseURL = "https://internal.example.com/"
languageCode = "en-us"
title = "Engineers' Blog"
theme = "dummy-theme"
defaultContentLanguage = "ja"
hasCJKLanguage = true
enableEmoji = true
pygmentsCodeFences = true
pygmentsStyle = "friendly"
enableGitInfo = true
enableRobotsTXT = true
#googleAnalytics = "UA-****-1"

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[languages]
[languages.en]
weight = 1
languageName = "English"

[languages.ja]
weight = 10
languageName = "日本語"
